name: diabetes-prediction-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9 # Specify a Python version compatible with Colab and MLflow
  - pip
  - pandas
  - scikit-learn
  - numpy
  - pip:
    - mlflow==2.13.2 # Specify a working MLflow version
